<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VolunteerEventsSeeder extends Seeder
{
    public function run()
    {
        DB::table('volunteer_events')->insert([
            [
                'title' => 'Beach Cleanup Drive',
                'location' => 'Mumbai Beach, Mumbai',
                'image' => 'storage/event/beach_cleanup.webp',
                'application_last_date' => '2025-07-27',
                'activity_start_date' => '2025-08-05',
                'duration' => '1 Day',
                'category' => 'Environmental',
                'details' => 'Join us in cleaning the Mumbai beach and raise awareness.',
                'qualification' => 'None',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tree Plantation Mission',
                'location' => 'Pune Park, Pune',
                'activity_start_date' => '2025-08-10',
                'image' => 'storage/event/tree_plantation.webp',
                'application_last_date' => Carbon::now()->addDays(12),
                'duration' => '1 Day',
                'category' => 'Environmental',
                'details' => 'Join us to plant trees and contribute to a greener planet.',
                'qualification' => 'None',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Food Distribution Drive',
                'location' => 'Mumbai Central, Mumbai',
                'activity_start_date' => '2025-08-15',
                'image' => 'storage/event/food_drive.jpg',
                'application_last_date' => Carbon::now()->addDays(10),
                'duration' => '2 Days',
                'category' => 'Hunger Relief',
                'details' => 'Help distribute food to the underprivileged across the city.',
                'qualification' => 'None',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Old Age Home Visit',
                'location' => 'Sector 12, Chandigarh',
                'activity_start_date' => '2025-08-20',
                'image' => 'storage/event/old_age_home.jepg',
                'application_last_date' => Carbon::now()->addDays(14),
                'duration' => '1 Day',
                'category' => 'Senior Care',
                'details' => 'Spend quality time with the elderly and assist in daily tasks.',
                'qualification' => 'None',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blood Donation Camp',
                'location' => 'Red Cross Bhavan, Delhi',
                'activity_start_date' => '2025-08-25',
                'image' => 'storage/event/blood_donation.jpg',
                'application_last_date' => Carbon::now()->addDays(15),
                'duration' => 'Half Day',
                'category' => 'Health',
                'details' => 'Donate blood and save lives by participating in our camp.',
                'qualification' => '18+ Age, Healthy',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Beach Cleanup Activity',
                'location' => 'Juhu Beach, Mumbai',
                'activity_start_date' => '2025-08-30',
                'image' => 'storage/event/beach_cleanup.webp',
                'application_last_date' => Carbon::now()->addDays(18),
                'duration' => '1 Day',
                'category' => 'Environmental',
                'details' => 'Be a part of our mission to keep the coastline clean.',
                'qualification' => 'None',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Women Empowerment Workshop',
                'location' => 'Lajpat Nagar, Delhi',
                'activity_start_date' => '2025-09-01',
                'image' => 'storage/event/women_empowerment.jpg',
                'application_last_date' => Carbon::now()->addDays(20),
                'duration' => '2 Days',
                'category' => 'Women',
                'details' => 'Help us organize workshops to educate and empower women.',
                'qualification' => 'Female Preferred',
                'gender' => 'Female',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Child Education Support',
                'location' => 'Govandi, Mumbai',
                'activity_start_date' => '2025-09-05',
                'image' => 'storage/event/child_education.jpg',
                'application_last_date' => Carbon::now()->addDays(22),
                'duration' => '7 Days',
                'category' => 'Children',
                'details' => 'Volunteer to teach and mentor underprivileged children.',
                'qualification' => 'Basic Education',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Animal Shelter Support',
                'location' => 'Whitefield, Bangalore',
                'activity_start_date' => '2025-09-10',
                'image' => 'storage/event/animal_shelter.webp',
                'application_last_date' => Carbon::now()->addDays(25),
                'duration' => '3 Days',
                'category' => 'Animal Welfare',
                'details' => 'Help care for rescued animals and support shelter staff.',
                'qualification' => 'Animal Friendly',
                'gender' => 'Any',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
